# Generated by Django 5.0.6 on 2026-06-05 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_weight', models.FloatField()),
                ('max_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience_years', models.IntegerField()),
                ('certification', models.CharField(blank=True, max_length=200)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ManyToManyField(related_name='coaches', to='core.fighttype')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('skill_level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('competitor', '竞技级')], default='beginner', max_length=20)),
                ('skill_score', models.IntegerField(default=0)),
                ('available_times', models.JSONField(default=list)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('fight_types', models.ManyToManyField(related_name='members', to='core.fighttype')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_goals', models.ManyToManyField(related_name='members', to='core.traininggoal')),
                ('weight_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.weightclass')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateTimeField()),
                ('weight_range_min', models.FloatField()),
                ('weight_range_max', models.FloatField()),
                ('skill_level_preference', models.CharField(blank=True, choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('competitor', '竞技级')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('open', '开放'), ('matched', '已配对'), ('expired', '已过期')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fighttype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='SkillProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=100)),
                ('mastery_level', models.IntegerField(default=0)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('fight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fighttype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progressions', to='core.member')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sessions', models.IntegerField(default=12)),
                ('sessions_per_week', models.IntegerField(default=3)),
                ('goals', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='core.coach')),
                ('fight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fighttype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', '已预约'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('performance_notes', models.TextField(blank=True)),
                ('techniques_practiced', models.JSONField(default=list)),
                ('attendance', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_sessions', to='core.coach')),
                ('fight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fighttype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='core.member')),
                ('training_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='FitnessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate_avg', models.IntegerField(blank=True, null=True)),
                ('heart_rate_max', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_fat', models.FloatField(blank=True, null=True)),
                ('flexibility_score', models.IntegerField(blank=True, null=True)),
                ('strength_score', models.IntegerField(blank=True, null=True)),
                ('endurance_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('training_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_data', to='core.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='SparringMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('pending', '待配对'), ('scheduled', '已安排'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('win', '胜利'), ('loss', '失败'), ('draw', '平局'), ('cancelled', '取消')], max_length=20, null=True)),
                ('match_notes', models.TextField(blank=True)),
                ('member1_score', models.IntegerField(blank=True, null=True)),
                ('member2_score', models.IntegerField(blank=True, null=True)),
                ('techniques_used', models.JSONField(default=list)),
                ('match_score', models.FloatField(default=0)),
                ('fight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fighttype')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparring_matches_lost', to='core.member')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparring_matches_as_1', to='core.member')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sparring_matches_as_2', to='core.member')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparring_matches_won', to='core.member')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weightclass')),
            ],
        ),
    ]
