# Generated by Django 5.0.6 on 2026-06-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weight_similarity_weight', models.FloatField(default=35)),
                ('skill_similarity_weight', models.FloatField(default=35)),
                ('time_compatibility_weight', models.FloatField(default=20)),
                ('fight_type_match_weight', models.FloatField(default=10)),
                ('recent_match_avoidance_weight', models.FloatField(default=5)),
                ('load_risk_penalty_weight', models.FloatField(default=30)),
                ('injury_risk_penalty_weight', models.FloatField(default=40)),
                ('max_allowed_weight_diff', models.FloatField(default=5)),
                ('max_allowed_skill_diff', models.IntegerField(default=2)),
                ('max_allowed_risk_score', models.FloatField(default=60)),
                ('min_recent_match_interval_days', models.IntegerField(default=3)),
                ('auto_block_high_risk', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryFatigueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('injury', '伤病'), ('fatigue', '疲劳'), ('rest', '休息需求')], max_length=20)),
                ('severity', models.CharField(choices=[('mild', '轻微'), ('moderate', '中等'), ('severe', '严重')], default='mild', max_length=20)),
                ('status', models.CharField(choices=[('active', '活动中'), ('recovered', '已恢复'), ('chronic', '慢性')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('affected_body_part', models.CharField(blank=True, max_length=100)),
                ('onset_date', models.DateField()),
                ('expected_recovery_date', models.DateField(blank=True, null=True)),
                ('actual_recovery_date', models.DateField(blank=True, null=True)),
                ('training_restriction_days', models.IntegerField(default=0)),
                ('no_sparring_days', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_fatigue_records', to='core.member')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_records', to='core.coach')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.CharField(choices=[('safe', '安全'), ('low', '低风险'), ('moderate', '中等风险'), ('high', '高风险'), ('dangerous', '危险')], default='safe', max_length=20)),
                ('risk_score', models.FloatField(default=0)),
                ('weight_diff_score', models.FloatField(default=0)),
                ('skill_diff_score', models.FloatField(default=0)),
                ('fatigue_risk_score', models.FloatField(default=0)),
                ('injury_risk_score', models.FloatField(default=0)),
                ('recent_match_penalty', models.FloatField(default=0)),
                ('risk_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True)),
                ('fight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fighttype')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments_as_1', to='core.member')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments_as_2', to='core.member')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(default='weekly', max_length=50)),
                ('target_load_per_week', models.FloatField(default=500)),
                ('max_load_per_week', models.FloatField(default=800)),
                ('max_sessions_per_week', models.IntegerField(default=5)),
                ('max_consecutive_training_days', models.IntegerField(default=3)),
                ('min_rest_days_per_week', models.IntegerField(default=1)),
                ('target_intensity', models.CharField(choices=[('very_light', '极轻量'), ('light', '轻量'), ('moderate', '中等'), ('intense', '高强度'), ('very_intense', '极高强度')], default='moderate', max_length=20)),
                ('max_intensity', models.CharField(choices=[('very_light', '极轻量'), ('light', '轻量'), ('moderate', '中等'), ('intense', '高强度'), ('very_intense', '极高强度')], default='intense', max_length=20)),
                ('allow_sparring', models.BooleanField(default=True)),
                ('max_sparring_per_week', models.IntegerField(default=2)),
                ('weight_gain_goal', models.FloatField(blank=True, null=True)),
                ('weight_loss_goal', models.FloatField(blank=True, null=True)),
                ('skill_improvement_goals', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_goals', to='core.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLoadAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('training_load_index', models.FloatField(default=0)),
                ('load_level', models.CharField(choices=[('very_low', '极低'), ('low', '低'), ('moderate', '中等'), ('high', '高'), ('very_high', '极高')], default='moderate', max_length=20)),
                ('recovery_status', models.CharField(choices=[('exhausted', '疲惫'), ('fatigued', '疲劳'), ('normal', '正常'), ('recovered', '恢复良好'), ('fresh', '状态极佳')], default='normal', max_length=20)),
                ('recovery_score', models.FloatField(default=50)),
                ('acute_load', models.FloatField(default=0)),
                ('chronic_load', models.FloatField(default=0)),
                ('acwr', models.FloatField(default=0)),
                ('fatigue_score', models.FloatField(default=0)),
                ('injury_risk_score', models.FloatField(default=0)),
                ('available_training_minutes', models.IntegerField(default=0)),
                ('recommended_intensity', models.CharField(default='moderate', max_length=50)),
                ('data_sources', models.JSONField(default=dict)),
                ('calculation_details', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_assessments', to='core.member')),
            ],
            options={
                'ordering': ['-assessment_date'],
                'unique_together': {('member', 'assessment_date')},
            },
        ),
    ]
